#!/bin/bash -eu

if [ "$BASH_SOURCE" != "$0" ]
then
  echo "$BASH_SOURCE must be executed, not sourced"
  return 1 # shouldn't use exit when sourced
fi

if [ "${FLOCKED:-}" != "$0" ]
then
  if FLOCKED="$0" flock -en -E 99 "$0" "$0" "$@" || case "$?" in
  99) echo already running
      exit 99
      ;;
  *)  exit $?
      ;;
  esac
  then
    # success
    exit 0
  fi
fi

# turning off hdmi saves a little bit of power
/usr/bin/tvservice -o

export LOG_FILE=/mutable/archiveloop.log

export CAM_MOUNT=/mnt/cam
export MUSIC_MOUNT=/mnt/music
export ARCHIVE_MOUNT=/mnt/archive
export MUSIC_ARCHIVE_MOUNT=/mnt/musicarchive

function log () {
  echo -n "$( date ): " >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

if [ ! -f /root/teslausb.conf ]
then
  log "couldn't find /root/teslausb.conf"
  exit 1
fi

source /root/teslausb.conf

if [ -z "${ARCHIVE_HOST_NAME+x}" ]
then
  log "ARCHIVE_HOST_NAME not set"
  exit 1
fi

function timestamp () {
  local prefix=${1:-}
  while IFS= read line
  do
    echo "$(date): $prefix$line"
  done
}

function fix_errors_in_mount_point () {
  local mount_point="$1"
  log "Running fsck on $mount_point..."
  local backingfile=$(mount | grep -w "$mount_point" | awk '{print $1}')
  local loopback=$(losetup -l | grep -w  "$backingfile" | awk '{print $1}')
  /sbin/fsck "$loopback" -- -a |& timestamp '| ' >> "$LOG_FILE" || echo ""
  log "Finished fsck on $mount_point."
}

function archive_is_reachable () {
  local reachable=true

  /root/bin/archive-is-reachable.sh "$ARCHIVE_HOST_NAME" || reachable=false

  if [ "$reachable" = false ]
  then
    false
    return
  fi
  true
}

function connect_usb_drives_to_host() {
  log "Connecting usb to host..."
  modprobe g_mass_storage
  log "Connected usb to host."
}

function wait_for_archive_to_be_reachable () {
  log "Waiting for archive to be reachable..."
  while [ true ]
  do
    if archive_is_reachable
    then
      log "Archive is reachable."
      break
    fi
    if [ -e /tmp/archive_is_reachable ]
    then
      log "Simulating archive is reachable"
      rm /tmp/archive_is_reachable
      break
    fi
    sleep 1
  done
}

function retry () {
  local attempts=0
  while [ true ]
  do
    if eval "$@"
    then
      true
      return
    fi
    if [ "$attempts" -ge 10 ]
    then
      log "Attempts exhausted."
      false
      return
    fi
    log "Sleeping before retry..."
    /bin/sleep 1
    attempts=$((attempts + 1))
    log "Retrying..."
  done
  false
  return
}

function mount_mountpoint () {
  local mount_point="$1"
  log "Mounting $mount_point..."

  local mounted=true
  mount "$mount_point" >> "$LOG_FILE" 2>&1 || mounted=false
  if [ "$mounted" = true ]
  then
    log "Mounted $mount_point."
    true
    return
  else
    log "Failed to mount $mount_point."
    false
    return
  fi
}

function ensure_mountpoint_is_mounted () {
  local mount_point="$1"
  local mount_exists=true

  findmnt --mountpoint "$mount_point" > /dev/null || mount_exists=false

  if [ "$mount_exists" = true ]
  then
    log "$mount_point is already mounted."
  else
    mount_mountpoint "$mount_point"
  fi
}

function ensure_mountpoint_is_mounted_with_retry () {
  retry ensure_mountpoint_is_mounted "$1"
}

function fix_errors_in_cam_file () {
  fix_errors_in_mount_point "$CAM_MOUNT"
}

function ensure_cam_file_is_mounted () {
  log "Ensuring cam file is mounted..."
  ensure_mountpoint_is_mounted_with_retry "$CAM_MOUNT"
  log "Ensured cam file is mounted."
}

function ensure_music_file_is_mounted () {
  log "Ensuring music backing file is mounted..."
  ensure_mountpoint_is_mounted_with_retry "$MUSIC_MOUNT"
  log "Ensured music drive is mounted."
}

function unmount_mount_point () {
  local mount_point="$1"
  log "Unmounting $mount_point..."
  if umount "$mount_point" >> "$LOG_FILE" 2>&1
  then
    log "Unmounted $mount_point."
  else
    log "Failed to unmount $mount_point, trying lazy unmount."
    if umount -l "$mount_point" >> "$LOG_FILE" 2>&1
    then
      log "lazily unmounted $mount_point"
    else
      log "lazy unmount failed"
    fi
  fi
}

function unmount_cam_file () {
  unmount_mount_point "$CAM_MOUNT"
}

function unmount_music_file () {
  unmount_mount_point "$MUSIC_MOUNT"
}

function fix_errors_in_music_file () {
  fix_errors_in_mount_point "$MUSIC_MOUNT"
}

function wait_for_archive_to_be_unreachable () {
  log "Waiting for archive to be unreachable..."
  while [ true ]
    do
      if ! retry archive_is_reachable
      then
        log "Archive is unreachable."
        break
      fi
      if [ -e /tmp/archive_is_unreachable ]
      then
        log "Simulating archive being unreachable."
        rm /tmp/archive_is_unreachable
        break
      fi
      sleep 1
  done
}

function check_if_usb_gadget_is_mounted () {
    if [ ! -d /sys/devices/platform/soc/20980000.usb/gadget/lun0 ]
    then
        log "USB Gadget not mounted. Fixing files and remounting..."
        disconnect_usb_drives_from_host
        mount_and_fix_errors_in_files
        connect_usb_drives_to_host
    fi
}

function mount_and_fix_errors_in_cam_file () {
  ensure_cam_file_is_mounted
  fix_errors_in_cam_file
  unmount_cam_file
}

function mount_and_fix_errors_in_music_file () {
  if [ -e "$MUSIC_MOUNT" ]
  then
    ensure_music_file_is_mounted
    fix_errors_in_music_file
    unmount_music_file
  fi
}

function mount_and_fix_errors_in_files () {
  mount_and_fix_errors_in_cam_file
  mount_and_fix_errors_in_music_file
}

function disconnect_usb_drives_from_host () {
  log "Disconnecting usb from host..."
  modprobe -r g_mass_storage
  log "Disconnected usb from host."
}

function archive_teslacam_clips () {
  log "Checking saved folder count..."
  
  ensure_cam_file_is_mounted

  fix_errors_in_cam_file
  
  DIR_COUNT=$(find "$CAM_MOUNT"/TeslaCam/SavedClips/* -maxdepth 0 -type d | wc -l)
  FILE_COUNT=$(find "$CAM_MOUNT"/TeslaCam/SavedClips/* -type f | wc -l)
  
  log "There are $DIR_COUNT event folder(s) with $FILE_COUNT file(s) to move."
  
  if [ $DIR_COUNT -gt 0 ]
  then
	log "Starting recording archiving..."

	/root/bin/send-push-message "TeslaUSB:" "Archiving $DIR_COUNT event folder(s) with $FILE_COUNT file(s) starting at $(date)"

	if [ -f /root/bin/tesla_api.py ]
	then
		while :
		do
		sleep 120
		/root/bin/tesla_api.py wake_up_vehicle >> "$LOG_FILE"
		done&
		WAKE_PID=$!
		log "wake up car process is $WAKE_PID"
	fi

	/root/bin/archive-clips.sh
	
  fi
  if [ ! -z "${WAKE_PID+x}" ]
  then
    log "killing PID $WAKE_PID"
    kill $WAKE_PID
  fi
  unmount_cam_file
}

function copy_music_files () {
  log "Starting music sync..."

  ensure_music_file_is_mounted

  fix_errors_in_music_file

  /root/bin/copy-music.sh

  unmount_music_file
}

function archive_clips () {
  log "Archiving..."

  disconnect_usb_drives_from_host

  if ! /root/bin/connect-archive.sh
  then
    log "Couldn't connect archive, skipping archive step"
    connect_usb_drives_to_host
    return
  fi

  if archive_teslacam_clips
  then
    log "Finished archiving."
  else
    log "Archiving failed."
  fi

  if timeout 5 [ -d "$MUSIC_ARCHIVE_MOUNT" -a -d "$MUSIC_MOUNT" ]
  then
    log "Copying music..."
    if copy_music_files
    then
      log "Finished copying music."
    else
      log "Copying music failed."
    fi
  else
    log "Music archive not configured or unreachable"
  fi

  /root/bin/disconnect-archive.sh

  connect_usb_drives_to_host
}

function truncate_log () {
  local log_length=$( wc -l "$LOG_FILE" | cut -d' ' -f 1 )
  if [ "$log_length" -gt 10000 ]
  then
    log "Truncating log..."
    local log_file2="${LOG_FILE}.2"
    tail -n 10000 "$LOG_FILE" > "${LOG_FILE}.2"
	mv "$log_file2" "$LOG_FILE"
  fi
}

function slowblink () {
  echo timer > /sys/class/leds/led0/trigger
  echo 900 > /sys/class/leds/led0/delay_on
  echo 100 > /sys/class/leds/led0/delay_off
}

function fastblink () {
  echo timer > /sys/class/leds/led0/trigger
  echo 150 > /sys/class/leds/led0/delay_on
  echo 50 > /sys/class/leds/led0/delay_off
}


function doubleblink () {
  echo heartbeat > /sys/class/leds/led0/trigger
  echo 1 > /sys/class/leds/led0/invert
}

function set_time () {
  log "Waiting for time to be set by ntpd..."
  for i in $(seq 1 10)
  do
    if ntp-wait --tries=1 --sleep=1
    then
      log "Time now set"
      return
    fi
    sleep 2
  done
  log "Time still not set, attempting to force it"
  if ! systemctl stop ntp
  then
    log "Failed to stop ntp daemon"
  fi
  if ! ntpd -q -x -g
  then
    log "Failed to set time"
  fi
  if ! systemctl start ntp
  then
    log "Failed to start ntp daemon"
  fi
}

function mount_all_snapshots {
  if ! stat /backingfiles/snapshots/snap-*/snap.bin &> /dev/null
  then
    log "no snapshots"
    return
  fi

  for img in /backingfiles/snapshots/snap-*/snap.bin
  do
    imgdir=$(dirname "$img")
    if mount | grep "$imgdir/mnt"
    then
      echo "$img already mounted"
      return
    fi
    /root/bin/mount_image.sh "$img" "$imgdir/mnt"
  done
}


function snapshotloop {
  while true
  do
    sleep 3500
    /root/bin/make_snapshot.sh
  done
}

export ARCHIVE_HOST_NAME
export -f mount_mountpoint
export -f ensure_mountpoint_is_mounted
export -f retry
export -f ensure_mountpoint_is_mounted_with_retry
export -f log

echo "==============================================" >> "$LOG_FILE"
log "Starting archiveloop..."

mount_all_snapshots
log "mounted all snapshots"

/root/bin/make_snapshot.sh

snapshotloop &

if archive_is_reachable
then
  fastblink

  set_time

  # archive_clips will fix errors in the cam file
  mount_and_fix_errors_in_music_file

  archive_clips

  doubleblink

  wait_for_archive_to_be_unreachable
else
  slowblink

  mount_and_fix_errors_in_files

  connect_usb_drives_to_host
fi

while [ true ]
do
  slowblink

  wait_for_archive_to_be_reachable

  fastblink

  set_time

  sleep ${ARCHIVE_DELAY:-20}

  # take a snapshot before archive_clips starts deleting files
  /root/bin/make_snapshot.sh

  archive_clips

  truncate_log

  doubleblink

  wait_for_archive_to_be_unreachable

  check_if_usb_gadget_is_mounted
done
