#!/bin/bash -eu

NUM_FILES_MOVED="$1"
TITLE="Dashcam Copy Complete"
MESSAGE="$NUM_FILES_MOVED files(s) were copied."

function log () {
  echo "$( date )" >> "$LOG_FILE"
  echo "$1" >> "$LOG_FILE"
}

function send_pushover () {
  log "Sending Pushover message for moved files."

  source /root/.teslaCamPushoverCredentials

  curl -F "token=$pushover_app_key" \
  -F "user=$pushover_user_key" \
  -F "title=$TITLE" \
  -F "message=$MESSAGE" \
  https://api.pushover.net/1/messages
}

function send_gotify () {
  log "Sending Gotify message for moved files."

  source /root/.teslaCamGotifySettings

  curl -X POST \
  -F "title=$TITLE" \
  -F "message=$MESSAGE" \
  -F "priority=$gotify_priority" \
  "$gotify_domain/message?token=$gotify_app_token" 
}

if [ $NUM_FILES_MOVED -gt 0 ]
then
  [ -r "/root/.teslaCamPushoverCredentials" ] && send_pushover
  [ -r "/root/.teslaCamGotifySettings" ] && send_gotify
fi
